# Generated by Django 5.1.6 on 2025-03-30 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_billinginfo_device_billinginfo_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdisbursementsetting',
            name='disbursement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_disbursement_setting_set', to='payments.paymentdisbursement'),
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_info_set', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_set', to='payments.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentdisbursementlog',
            name='payment_disbursement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_disbursement_log_set', to='payments.paymentdisbursement'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_log_set', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_set', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refundlog',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_log_set', to='payments.refund'),
        ),
    ]
