# Generated by Django 5.1.6 on 2025-03-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
