# Generated by Django 5.1.6 on 2025-03-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_stack_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stack_logos'),
        ),
    ]
