# Generated by Django 5.1.6 on 2025-03-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menumeta',
            old_name='title',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='menumeta',
            name='order',
        ),
    ]
