# Generated by Django 5.1.6 on 2025-02-27 19:50

import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('program', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProgramModuleWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('program_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programmodule')),
            ],
            options={
                'ordering': ['week'],
                'unique_together': {('program_module', 'week')},
            },
        ),
        migrations.CreateModel(
            name='ProgramModuleWeekLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', markdownx.models.MarkdownxField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('learning_model', models.CharField(choices=[('SOLO', 'Solo'), ('GROUP', 'Group'), ('HYBRID', 'Hybrid')], default='SOLO', max_length=40)),
                ('lession_type', models.CharField(choices=[('NORMAL', 'Normal'), ('QUIZ', 'Quiz'), ('WEEKLY_CAPSTONE', 'Weekly Capstone'), ('MIDTERM_CAPSTONE', 'Midterm Capstone'), ('FINAL_CAPSTONE', 'Final Capstone')], default='NORMAL', max_length=40)),
                ('duration', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('program_module_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programmoduleweek')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('program_module_week', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserLearningLessonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED_FOR_REVIEW', 'Submitted for Review'), ('REVIEWED_AND_APPROVED', 'Reviewed and Approved'), ('REVIEWED_AND_REJECTED', 'Reviewed and Rejected'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='NOT_STARTED', max_length=40)),
                ('program_module_week_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programmoduleweeklesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
