# Generated by Django 5.1.6 on 2025-02-27 22:04

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_programmodule_programmoduleweek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmoduleweeklesson',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
