# Generated by Django 5.1.6 on 2025-02-27 22:16

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_programmoduleweeklesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmoduleweeklesson',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
