# Generated by Django 5.1.6 on 2025-02-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_programmoduleweeklesson_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='programcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='programcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='programfeedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='programfeedback',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userenrollmentprogram',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userenrollmentprogram',
            name='updated_at',
        ),
    ]
