# Generated by Django 5.1.6 on 2025-03-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0001_initial'),
        ('programs', '0008_program_deleted_at_program_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmodule',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programmodule',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_manager.menumeta'),
        ),
        migrations.AddField(
            model_name='programmoduleweek',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programmoduleweek',
            name='meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_manager.menumeta'),
        ),
        migrations.AddField(
            model_name='programmoduleweek',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programmodule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
