# Generated by Django 5.1.6 on 2025-03-03 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_alter_programmodule_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmoduleweek',
            options={'ordering': ['week'], 'verbose_name_plural': 'Program Module Weeks'},
        ),
        migrations.AlterUniqueTogether(
            name='userlearninglessonstatus',
            unique_together={('user', 'program_module_week_lesson')},
        ),
    ]
