# Generated by Django 5.1.6 on 2025-03-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_alter_programmoduleweek_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmoduleweeklesson',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
