# Generated by Django 5.1.6 on 2025-03-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_alter_programmoduleweeklesson_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrollmentprogram',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('pending', 'Pending'), ('paused', 'Paused'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
