# Generated by Django 5.1.6 on 2025-03-08 11:01

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_alter_userenrollmentprogram_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmoduleweek',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
