# Generated by Django 5.1.6 on 2025-03-09 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_programmoduleweek_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearninglessonstatus',
            name='program_module_week_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_status', to='programs.programmoduleweeklesson'),
        ),
    ]
