# Generated by Django 5.1.6 on 2025-03-11 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_programrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programrating',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='programs.program'),
        ),
    ]
