# Generated by Django 5.1.6 on 2025-03-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_alter_programrating_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=200),
        ),
    ]
