# Generated by Django 5.1.6 on 2025-03-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0024_program_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmoduleweeklesson',
            old_name='lession_type',
            new_name='lesson_type',
        ),
    ]
