# Generated by Django 5.1.6 on 2025-03-19 14:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0025_rename_lession_type_programmoduleweeklesson_lesson_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userenrollmentprogram',
            unique_together={('user', 'program')},
        ),
    ]
