# Generated by Django 5.1.6 on 2025-03-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0026_alter_userenrollmentprogram_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearninglessonstatus',
            name='is_to_be_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlearninglessonstatus',
            name='pr_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlearninglessonstatus',
            name='pr_review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlearninglessonstatus',
            name='pr_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
