# Generated by Django 5.1.6 on 2025-03-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0027_userlearninglessonstatus_is_to_be_reviewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlearninglessonstatus',
            name='pr_review_comment',
        ),
    ]
