# Generated by Django 5.1.6 on 2025-03-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0031_programstack_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstack',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
