# Generated by Django 5.1.6 on 2025-03-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0033_alter_programstack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
