# Generated by Django 5.1.6 on 2025-03-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0034_program_publication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
