# Generated by Django 5.1.6 on 2025-03-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0035_program_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmoduleweeklesson',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
