# Generated by Django 5.1.6 on 2025-03-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0036_programmoduleweeklesson_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmoduleweeklesson',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
