# Generated by Django 5.1.6 on 2025-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0037_alter_programmoduleweeklesson_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodule',
            name='name',
            field=models.CharField(blank=True, default='program-module', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programmoduleweek',
            name='name',
            field=models.CharField(blank=True, default='weekly-lessons', max_length=255, null=True),
        ),
    ]
