# Generated by Django 5.1.6 on 2025-03-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0038_alter_programmodule_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programmodule',
            unique_together=set(),
        ),
    ]
