# Generated by Django 5.1.6 on 2025-03-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0039_alter_programmodule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmodule',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='programmoduleweek',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='programmoduleweeklesson',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='programpayment',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='userlearninglessonstatus',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
