# Generated by Django 5.1.6 on 2025-04-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0040_programmodule_publication_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstack',
            name='description',
        ),
        migrations.RemoveField(
            model_name='programstack',
            name='name',
        ),
    ]
