# Generated by Django 5.1.6 on 2025-04-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0041_remove_programstack_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmoduleweek',
            name='week',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
