# Generated by Django 5.1.6 on 2025-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0042_alter_programmoduleweek_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmoduleweeklesson',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
