# Generated by Django 5.1.6 on 2025-04-07 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0044_alter_userenrollmentprogram_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_set', to='programs.program'),
        ),
    ]
